import { Product } from "@/lib/types";

export const mockData: Product[] = [
  {
    id: 1,
    title: "Laptop Dell XPS 13",
    description: "Mỏng nhẹ, mạnh mẽ cho dân văn phòng.",
    price: 28000000,
    oldPrice: 32000000,
    discount: "12%",
    image: "/images/laptop1.jpg",
    body: "Chi tiết sản phẩm...",
    name: "Laptop Dell XPS 13",
  },
  {
    id: 2,
    title: "PC Gaming ROG Strix",
    description: "Chiến mọi tựa game, build đỉnh.",
    price: 45000000,
    oldPrice: 50000000,
    discount: "10%",
    image: "/images/pc1.jpg",
    body: "Chi tiết sản phẩm...",
    name: "PC Gaming ROG Strix",
  },
  {
    id: 3,
    title: "PC Gaming ROG Strix",
    description: "Chiến mọi tựa game, build đỉnh.",
    price: 45000000,
    oldPrice: 50000000,
    discount: "10%",
    image: "/images/pc1.jpg",
    body: "Chi tiết sản phẩm...",
    name: "PC Gaming ROG Strix",
  },
  {
    id: 4,
    title: "PC Gaming ROG Strix",
    description: "Chiến mọi tựa game, build đỉnh.",
    price: 45000000,
    oldPrice: 50000000,
    discount: "10%",
    image: "/images/pc1.jpg",
    body: "Chi tiết sản phẩm...",
    name: "PC Gaming ROG Strix",
  },
  {
    id: 5,
    title: "PC Gaming ROG Strix",
    description: "Chiến mọi tựa game, build đỉnh.",
    price: 45000000,
    oldPrice: 50000000,
    discount: "10%",
    image: "/images/pc1.jpg",
    body: "Chi tiết sản phẩm...",
    name: "PC Gaming ROG Strix",
  },
];
