export const subMenuData: Record<string, Record<string, string[]>> = {
  Laptop: {
    "Thương hiệu": ["ASUS", "ACER", "MSI", "LENOVO", "DELL", "HP", "LG"],
    "Giá bán": [
      "Dưới 15 triệu",
      "Từ 15 đến 20 triệu",
      "20 triệu đến 30 triệu",
      "Trên 30 triệu",
    ],
    "CPU INTEL-AMD": [
      "Intel Core i3",
      "Intel Core i5",
      "Intel Core i7",
      "AMD Ryzen",
    ],
    "Nhu cầu sử dụng": [
      "Học sinh sinh viên",
      "Thiết kế đồ Họa",
      "Nhân viên văn phòng",
      "Mỏng nhẹ,cao cấp",
    ],
    "Linh phụ kiện Laptop": ["Ram Laptop", "SSD Laptop", "Ổ cứng di động"],
    "Laptop ASUS": ["ASUS OLED Series", "Vivobook Series", "Zenbook Series"],
    "Laptop ACER": ["Aspire Series", "Swift Series"],
    "Laptop MSI": ["Modem Series", "Prestige Series", "Summit Series"],
    "Laptop LENOVO": [
      "ThinkBook Series",
      "IdeaPad Series",
      "IdeaPad Pro Series",
      "ThinkPad Series",
      "Yoga Series",
    ],
    "Laptop DELL": [
      "Inspiron Series",
      "Vostro Series",
      "Latitude Series",
      "XPS Series",
    ],
  },
  "Laptop Gaming": {
    "Thương hiệu": [
      "ROG",
      "Alienware",
      "Predator",
      "ACER / PREDATOR",
      "MSI",
      "LENOVO",
      "DELL",
      "HP",
      "GIGABYTE / AORUS",
    ],
    "Giá bán": [
      "Dưới 15 triệu",
      "Từ 15 đến 20 triệu",
      "20 triệu đến 30 triệu",
      "Trên 30 triệu",
      "Gaming cao cấp RTX 40 Series ",
      "Gaming cao cấp RTX 50 Series",
    ],
    "ACER | PREDATOR": [
      "Nitro Series",
      "Aspire Series",
      "Predator Series",
      "ACER RTX 40 Series",
      "ACER RTX 50 Series",
    ],
    "ACER | ROG Gaming": [
      "ROG Series",
      "TUF Series",
      "Zephyrus Series",
      "ROG Strix G",
      "ROG Flow Series",
      "ROG Ally",
    ],
    "MSI Gaming": [
      "Titan GS Series",
      "Stealth GE Series",
      "Raider GE Series",
      "Vector GP Series",
      "Crosshair / Pulse GL Series",
      "Sword / Katana GF66 Series",
      "Cyborg / Thin GF Series",
      "MSi RTX 50 Series",
    ],
    "LENOVO Gaming": ["Legion Gaming", "LOQ series"],
    "DELL Gaming": [
      "Dell Gaming G series",
      "Alienware series",
      "Dell RTX 40 Series",
    ],
    "HP Gaming": ["HP Victus", "HP Omen"],
    "Card độ họa": [
      "RTX 3050 / 3050Ti",
      "RTX 3060",
      "RTX 3070 / 3080",
      "AMD Radeon RX",
      "RTX 40 Series",
      "RTX 50 Series",
    ],
    "Linh - Phụ kiện Laptop": ["Ram laptop", "SSD laptop", "Ổ cứng di động"],
  },
  "Main, CPU, VGA": {
    "VGA RTX 50 SERIES": ["RTX 5090", "RTX 5080", "RTX 5070Ti", "RTX 5070"],
    "VGA (Trên 12 GB VRAM": [
      "RTX 4070 SUPER (12GB)",
      "RTX 4070Ti SUPER (16GB)",
      "RTX 4080 SUPER (16GB)",
      "RTX 4090 SUPER (24GB)",
    ],
    "VGA (Dưới 12 GB VRAM)": [
      "RTX 4060Ti (8-16GB)",
      "RTX 4060 (8GB)",
      "RTX 3060 (12GB)",
      "RTX 3050 (12GB)",
      "GTX 1650 (4GB)",
      "GT 710 / GT 1030 (2-4GB)",
    ],
    "VGA - Card màn hình ": ["NVIDIA Quadro", "AMD Radeon"],
    "Bo mạch chủ Intel": [
      "Z890 (Mới)",
      "Z790",
      "B760",
      "H610",
      "X299X",
      "Xem tất cả",
    ],
    "Bo mạch chủ AMD": [
      "AMD X870 (Mới)",
      "AMD X670",
      "AMD X570",
      "AMD B650 (Mới)",
      "AMD B550",
      "AMD A320",
      "AMD TRX40",
    ],
    "CPU - Bộ vi xử lý intel": [
      "CPU Intel Core Ultra Series 2 (Mới)",
      "CPU Intel 9",
      "CPU Intel 7",
      "CPU Intel 5",
      "CPU Intel 3",
    ],
    "CPU - Bộ vi xử lý AMD": [
      "CPU AMD Athlon",
      "CPU AMD R3",
      "CPU AMD R5",
      "CPU AMD R7",
      "CPU AMD R9",
    ],
  },
  "Case, Nguồn Tản": {
    "Case - Theo Hãng": [
      "Case ASUS",
      "Case Corsair",
      "Case Lianli",
      "Case NZXT",
      "Case Inwin",
      "Case Thermaltake",
      "Xem tất cả",
    ],
    "Case - Theo Giá": [
      "Dưới 1 triệu",
      "Từ 1 triệu đến 2 triệu",
      "Trên 2 triệu",
      "Xem tất cả",
    ],
    "Nguồn - Theo Hãng": [
      "Nguồn ASUS",
      "Nguồn DeepCool",
      "Nguồn Corsair",
      "Nguồn NZXT",
      "Nguồn MSI",
      "Xem tất cả",
    ],
    "Nguồn - Theo công suất": [
      "Từ 400w-500w",
      "Từ 500w-600w",
      "Từ 600w-700w",
      "Từ 700w-800w",
      "Trên 1000w",
      "Xem tất cả",
    ],
    "Phụ Kiện Pc": [
      "Dây LED",
      "Dây rise - Dựng VGA",
      "Giá đỡ VGA",
      "Keo tản nhiệt",
      "Xem tất cả",
    ],
    "Loại tản nhiệt": [
      "Tản nhiệt AIO 240mm",
      "Tản nhiệt AIO 280mm",
      "Tản nhiệt AIO 360mm",
      "Tản nhiệt AIO 420mm",
      "Tản nhiệt khí",
      "Fan RGB",
      "Xem tất cả",
    ],
  },
  "Ổ cứng, Ram, Thẻ nhớ": {
    "Dung lượng RAM": ["8 GB", "16 GB", "32 GB", "64 GB", "Xem tất cả"],
    "Loại RAM": ["DDR4", "DDR5", "Xem tất cả"],
    "Hãng RAM": ["Corsair", "Kingston", "G.Skill", "PNY", "Xem tất cả"],
    "Dung lượng HDD": [
      "HDD 1 TB",
      "HDD 2 TB",
      "HDD 4 TB - 6 TB",
      "HDD trên 8TB",
      "Xem tất cả",
    ],
    "Hãng HDD": ["WesterDigital", "Seagate", "Toshiba", "Xem tất cả"],
    "Dung lượng SSD": [
      "120GB - 128GB",
      "250GB - 256GB",
      "480GB - 512GB",
      "960GB - 1TB",
      "2TB",
      "Trên 2TB",
      "Xem tất cả",
    ],
    "Hãng SSD": [
      "Samsung",
      "Wester Digital",
      "Kingston",
      "Corsair",
      "PNY",
      "Xem tất cả",
    ],
    "Thẻ nhớ / USB": ["Sandisk"],
    "Ổ cứng di động": ["Xem tất cả"],
  },
  "Loa, Micro, Webcam": {
    "Thương hiệu loa": ["Edifier", "Razer", "Logitech", "SoundMax"],
    "Kiểu Loa": [
      "Loa vi tính",
      "Loa Bluetooth",
      "Loa Soundbar",
      "Loa mini",
      "Sub phụ (Loa trầm)",
    ],
    Webcam: [
      "Độ phân giải 4k",
      "Độ phân giải Full HD (1080p)",
      "Độ phân giải 720p",
    ],
    Microphone: ["Micro HyperX"],
  },
  "Màn Hình": {
    "Hãng sản xuất": [
      "LG",
      "Asus",
      "ViewSonic",
      "Dell",
      "Gigabyte",
      "AOC",
      "Acer",
      "HKC",
      "MSI",
      "Lenovo",
      "E-Dra",
      "Xem tất cả",
    ],
    "Giá tiền": [
      "Dưới 5 triệu",
      "Từ 5 đến 10 triệu",
      "Từ 10 đến 20 triệu",
      "Từ 20 đến 30 triệu",
      "Trên 30 triệu",
    ],
    "Độ phân giải": [
      "Màn hình Full HD",
      "Màn hình 2k 1440p",
      "Màn hình 4k UHD",
      "Màn hình 6k",
    ],
    "Tần số quét": ["60Hz", "75Hz", "100Hz", "144Hz", "240Hz"],
    "Màn hình cong": [
      "24` Curved",
      "24` Curved",
      "24` Curved",
      "Trên 32` Cirverd",
    ],
    "Kích thước": [
      "Màn hình 22`",
      "Màn hình 24`",
      "Màn hình 27`",
      "Màn hình 29`",
      "Màn hình 32`",
      "Màn hình trên 32`",
      "Hỗ trợ giá treo (VESA)",
    ],
    "Màn hình độ họa": [
      "Màn hình độ họa 24`",
      "Màn hình độ họa 27`",
      "Màn hình độ họa 32`",
    ],
    "Phụ kiện màn hình": ["Giá treo màn hình", "Phụ kiện dây HDMI, DP, LAN"],
    "Màn hình di động": ["Full HD 1080p", "2k 1440p", "Có cảm ứng"],
  },
  "Bàn Phím": {
    "Thương hiệu": [
      "AKKO",
      "AULA",
      "Dare-U",
      "Durgod",
      "FL-Esports",
      "Corsair",
      "E-Dra",
      "Cidoo",
      "Machenike",
      "ASUS",
      "Logitech",
      "Razer",
      "Leopold",
      "Steelseries",
      "Rapoo",
      "VGN",
    ],
    "Giá tiền": [
      "Dưới 1 triệu",
      "1 triệu - 2 triệu",
      "2 triệu - 3 triệu",
      "3 triệu - 4 triệu",
      "Trên 4 triệu",
    ],
    "Kết nối": ["Bluetooth", "Wireless"],
    "Phụ kiện bàn phím cơ": ["Keycaps", "Dwarf Factory", "Kê tay"],
  },
  "Chuột + Lót Chuột": {
    "Thương hiệu chuột": [
      "Logitech",
      "Razer",
      "Corsair",
      "Pulsar",
      "Microsoft",
      "Dare U",
    ],
    "Thương hiệu chuột (khác)": ["ASUS", "Steelseries", "Glorious", "Rapoo"],
    "Chuột theo giá tiền": [
      "Dưới 500 nghìn",
      "Từ 500 nghìn - 1 triệu",
      "Từ 1 triệu - 2 triệu",
      "Trên 2 triệu - 3 triệu",
      "Trên 3 triệu",
    ],
    "Loại Chuột": ["Chuột chơi game", "Chuột văn phòng"],
    Logitech: ["Logitech Gaming", "Logitech Văn phòng"],
    "Thương hiệu lót chuột": [
      "GEARVN",
      "ASUS",
      "Steelseries",
      "Dare-U",
      "Razer",
    ],
    "Các loại lót chuột": ["Mềm", "Cứng", "Dày", "Mỏng", "Viền có led"],
    "Lót chuột theo size": ["Nhỏ", "Vừa", "Lớn"],
  },
  "Tai Nghe": {
    "Thương hiệu tai nghe": [
      "ASUS",
      "HyperX",
      "Corsair",
      "Razer",
      "Steelseries",
      "Rapoo",
      "Logitech",
      "Edifier",
    ],
    "Tai nghe theo giá": [
      "Tai nghe dưới 1 triệu",
      "Tai nghe 1 triệu đến 2 triệu",
      "Tai nghe 2 đến 3 triệu",
      "Tai nghe 3 đến 4 triệu",
      "Tai nghe trên 4 triệu",
    ],
    "Kiểu kết nối": ["Tai nghe Wireless", "Tai nghe Bluetooth"],
    "Kiểu tai nghe": ["Tai nghe Over-ear", "Tai nghe Gaming In-ear"],
  },
  "Bàn - Ghế": {
    "Thương hiệu ghế gaming": [
      "DXRacer",
      "AKRacing",
      "Anda Seat",
      "Corsair",
      "Razer",
    ],
    "Ghế gaming theo giá": [
      "Dưới 3 triệu",
      "Từ 3 triệu - 5 triệu",
      "Từ 5 triệu - 7 triệu",
      "Trên 7 triệu",
    ],
    "Thương hiệu bàn gaming": ["E-Dra", "DXRacer", "Furos", "Warrior", "Razer"],
    "Bàn gaming theo giá": [
      "Dưới 2 triệu",
      "Từ 2 triệu - 4 triệu",
      "Từ 4 triệu - 6 triệu",
      "Trên 6 triệu",
    ],
  },
  "Phần Mềm, Mạng": {
    "Phần mềm": [
      "Windows",
      "Microsoft Office",
      "Phần mềm diệt virus",
      "Phần mềm thiết kế đồ họa",
      "Phần mềm lập trình",
    ],
    "Thương hiệu phần mềm": [
      "Microsoft",
      "Adobe",
      "Autodesk",
      "Kaspersky",
      "ESET",
    ],
    "Thiết bị mạng": [
      "Router Wi-Fi",
      "Bộ mở rộng sóng",
      "Modem",
      "Switch mạng",
      "Card mạng",
    ],
    "Thương hiệu thiết bị mạng": [
      "TP-Link",
      "ASUS",
      "Netgear",
      "D-Link",
      "MikroTik",
    ],
    "Thiết bị mạng theo giá": [
      "Dưới 500 nghìn",
      "Từ 500 nghìn - 1 triệu",
      "Từ 1 triệu - 2 triệu",
      "Trên 2 triệu",
    ],
  },
  "Handheld, Console": {
    "Thiết bị chơi game cầm tay": [
      "Nintendo Switch",
      "Steam Deck",
      "ASUS ROG Ally",
      "PlayStation Portal",
    ],
    Console: [
      "PlayStation 5",
      "Xbox Series X",
      "Xbox Series S",
      "PlayStation 4",
    ],
    "Thương hiệu console & handheld": [
      "Sony",
      "Microsoft",
      "Nintendo",
      "ASUS",
      "Valve",
    ],
    "Phụ kiện console": [
      "Tay cầm chơi game",
      "Dock sạc",
      "Tai nghe gaming",
      "Bộ nhớ mở rộng",
    ],
    "Console theo giá": [
      "Dưới 5 triệu",
      "Từ 5 triệu - 10 triệu",
      "Từ 10 triệu - 15 triệu",
      "Trên 15 triệu",
    ],
  },
  "Một số dịch vụ khác": {
    "Dịch vụ bảo hành": [
      "Gia hạn bảo hành",
      "Bảo hành VIP",
      "Bảo hành tận nơi",
    ],
    "Dịch vụ lắp đặt": [
      "Lắp đặt PC",
      "Lắp đặt Gaming Gear",
      "Lắp đặt thiết bị văn phòng",
    ],
    "Dịch vụ sửa chữa": [
      "Sửa chữa Laptop",
      "Sửa chữa PC",
      "Sửa chữa Gaming Gear",
      "Sửa chữa Console",
    ],
    "Dịch vụ phần mềm": [
      "Cài đặt Windows",
      "Cài đặt phần mềm văn phòng",
      "Cài đặt game bản quyền",
    ],
    "Dịch vụ mạng": [
      "Lắp đặt mạng nội bộ",
      "Tư vấn và lắp đặt WiFi",
      "Cấu hình Router & Modem",
    ],
  },
};
